#!/bin/bash

WORD_FILE_PATHNAME=/usr/share/dict/words go run main.go &

sleep 1

http-spec -hostname localhost -scheme http endpoints/get-error-anticipated.htsf   \
                                           endpoints/get-error-unanticipated.htsf \
                                           endpoints/post-game.htsf               \
                                           endpoints/put-game.htsf                \
                                           endpoints/put-game-secret-word.htsf    \
                                           endpoints/get-game.htsf                \
                                           endpoints/get-game-secret-word.htsf    \
                                           endpoints/post-games.htsf

ps auxw | grep [g]o-build | awk '{print $2}' | xargs kill
